syntax = "proto3";

package booking;

option go_package = "cinema-reservation/common/proto/pb";

service BookingService {
  rpc GetSeats(SeatsRequest) returns (SeatsResponse);
  
  rpc ReserveSeat(ReserveRequest) returns (ReserveResponse);
}

message SeatsRequest {
  string projection_id = 1;
}

message SeatsResponse {
  string projection_id = 1;
  map<int32, bool> seats = 2;
}

message ReserveRequest {
  string projection_id = 1;
  int32 seat_id = 2;
  string user_id = 3;
}

message ReserveResponse {
  bool success = 1;
  string message = 2;
  string booking_id = 3;
}
