syntax = "proto3";

package catalog;

option go_package = "cinema-reservation/common/proto/pb";

service CatalogService {
  rpc GetMovies(Empty) returns (MovieList);
  rpc GetMovie(MovieRequest) returns (Movie);
  rpc GetProjections(Empty) returns (ProjectionList);
  rpc GetProjectionsByMovie(MovieRequest) returns (ProjectionList);
  rpc GetProjection(ProjectionRequest) returns (Projection);
}

message Empty {}

message MovieRequest {
  string id = 1;
}

message Movie {
  string id = 1;
  string title = 2;
  string category = 3;
}

message Projection {
  string id = 1;
  string movie_id = 2;
  string show_time = 3;
  string room_id = 4;      
  int32 total_seats = 5;
}

message ProjectionList {
  repeated Projection projections = 1;
}

message ProjectionRequest {
  string id = 1;
}

message MovieList {
  repeated Movie movies = 1;
}
