// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: common/proto/booking.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectionId  string                 `protobuf:"bytes,1,opt,name=projection_id,json=projectionId,proto3" json:"projection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatsRequest) Reset() {
	*x = SeatsRequest{}
	mi := &file_common_proto_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatsRequest) ProtoMessage() {}

func (x *SeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatsRequest.ProtoReflect.Descriptor instead.
func (*SeatsRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_booking_proto_rawDescGZIP(), []int{0}
}

func (x *SeatsRequest) GetProjectionId() string {
	if x != nil {
		return x.ProjectionId
	}
	return ""
}

type SeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectionId  string                 `protobuf:"bytes,1,opt,name=projection_id,json=projectionId,proto3" json:"projection_id,omitempty"`
	Seats         map[int32]bool         `protobuf:"bytes,2,rep,name=seats,proto3" json:"seats,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // ID Posto -> Occupato
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatsResponse) Reset() {
	*x = SeatsResponse{}
	mi := &file_common_proto_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatsResponse) ProtoMessage() {}

func (x *SeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatsResponse.ProtoReflect.Descriptor instead.
func (*SeatsResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_booking_proto_rawDescGZIP(), []int{1}
}

func (x *SeatsResponse) GetProjectionId() string {
	if x != nil {
		return x.ProjectionId
	}
	return ""
}

func (x *SeatsResponse) GetSeats() map[int32]bool {
	if x != nil {
		return x.Seats
	}
	return nil
}

type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectionId  string                 `protobuf:"bytes,1,opt,name=projection_id,json=projectionId,proto3" json:"projection_id,omitempty"`
	SeatId        int32                  `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_common_proto_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_booking_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveRequest) GetProjectionId() string {
	if x != nil {
		return x.ProjectionId
	}
	return ""
}

func (x *ReserveRequest) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *ReserveRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BookingId     string                 `protobuf:"bytes,3,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveResponse) Reset() {
	*x = ReserveResponse{}
	mi := &file_common_proto_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResponse) ProtoMessage() {}

func (x *ReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResponse.ProtoReflect.Descriptor instead.
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_booking_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReserveResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

var File_common_proto_booking_proto protoreflect.FileDescriptor

const file_common_proto_booking_proto_rawDesc = "" +
	"\n" +
	"\x1acommon/proto/booking.proto\x12\abooking\"3\n" +
	"\fSeatsRequest\x12#\n" +
	"\rprojection_id\x18\x01 \x01(\tR\fprojectionId\"\xa7\x01\n" +
	"\rSeatsResponse\x12#\n" +
	"\rprojection_id\x18\x01 \x01(\tR\fprojectionId\x127\n" +
	"\x05seats\x18\x02 \x03(\v2!.booking.SeatsResponse.SeatsEntryR\x05seats\x1a8\n" +
	"\n" +
	"SeatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"g\n" +
	"\x0eReserveRequest\x12#\n" +
	"\rprojection_id\x18\x01 \x01(\tR\fprojectionId\x12\x17\n" +
	"\aseat_id\x18\x02 \x01(\x05R\x06seatId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"d\n" +
	"\x0fReserveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x03 \x01(\tR\tbookingId2\x8d\x01\n" +
	"\x0eBookingService\x129\n" +
	"\bGetSeats\x12\x15.booking.SeatsRequest\x1a\x16.booking.SeatsResponse\x12@\n" +
	"\vReserveSeat\x12\x17.booking.ReserveRequest\x1a\x18.booking.ReserveResponseB$Z\"cinema-reservation/common/proto/pbb\x06proto3"

var (
	file_common_proto_booking_proto_rawDescOnce sync.Once
	file_common_proto_booking_proto_rawDescData []byte
)

func file_common_proto_booking_proto_rawDescGZIP() []byte {
	file_common_proto_booking_proto_rawDescOnce.Do(func() {
		file_common_proto_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_booking_proto_rawDesc), len(file_common_proto_booking_proto_rawDesc)))
	})
	return file_common_proto_booking_proto_rawDescData
}

var file_common_proto_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_proto_booking_proto_goTypes = []any{
	(*SeatsRequest)(nil),    // 0: booking.SeatsRequest
	(*SeatsResponse)(nil),   // 1: booking.SeatsResponse
	(*ReserveRequest)(nil),  // 2: booking.ReserveRequest
	(*ReserveResponse)(nil), // 3: booking.ReserveResponse
	nil,                     // 4: booking.SeatsResponse.SeatsEntry
}
var file_common_proto_booking_proto_depIdxs = []int32{
	4, // 0: booking.SeatsResponse.seats:type_name -> booking.SeatsResponse.SeatsEntry
	0, // 1: booking.BookingService.GetSeats:input_type -> booking.SeatsRequest
	2, // 2: booking.BookingService.ReserveSeat:input_type -> booking.ReserveRequest
	1, // 3: booking.BookingService.GetSeats:output_type -> booking.SeatsResponse
	3, // 4: booking.BookingService.ReserveSeat:output_type -> booking.ReserveResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_booking_proto_init() }
func file_common_proto_booking_proto_init() {
	if File_common_proto_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_booking_proto_rawDesc), len(file_common_proto_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_booking_proto_goTypes,
		DependencyIndexes: file_common_proto_booking_proto_depIdxs,
		MessageInfos:      file_common_proto_booking_proto_msgTypes,
	}.Build()
	File_common_proto_booking_proto = out.File
	file_common_proto_booking_proto_goTypes = nil
	file_common_proto_booking_proto_depIdxs = nil
}
