// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: common/proto/catalog.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_GetMovies_FullMethodName             = "/catalog.CatalogService/GetMovies"
	CatalogService_GetMovie_FullMethodName              = "/catalog.CatalogService/GetMovie"
	CatalogService_GetProjections_FullMethodName        = "/catalog.CatalogService/GetProjections"
	CatalogService_GetProjectionsByMovie_FullMethodName = "/catalog.CatalogService/GetProjectionsByMovie"
	CatalogService_GetProjection_FullMethodName         = "/catalog.CatalogService/GetProjection"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	GetMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MovieList, error)
	GetMovie(ctx context.Context, in *MovieRequest, opts ...grpc.CallOption) (*Movie, error)
	GetProjections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProjectionList, error)
	GetProjectionsByMovie(ctx context.Context, in *MovieRequest, opts ...grpc.CallOption) (*ProjectionList, error)
	GetProjection(ctx context.Context, in *ProjectionRequest, opts ...grpc.CallOption) (*Projection, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) GetMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MovieList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MovieList)
	err := c.cc.Invoke(ctx, CatalogService_GetMovies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetMovie(ctx context.Context, in *MovieRequest, opts ...grpc.CallOption) (*Movie, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Movie)
	err := c.cc.Invoke(ctx, CatalogService_GetMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetProjections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProjectionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectionList)
	err := c.cc.Invoke(ctx, CatalogService_GetProjections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetProjectionsByMovie(ctx context.Context, in *MovieRequest, opts ...grpc.CallOption) (*ProjectionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectionList)
	err := c.cc.Invoke(ctx, CatalogService_GetProjectionsByMovie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetProjection(ctx context.Context, in *ProjectionRequest, opts ...grpc.CallOption) (*Projection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Projection)
	err := c.cc.Invoke(ctx, CatalogService_GetProjection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
type CatalogServiceServer interface {
	GetMovies(context.Context, *Empty) (*MovieList, error)
	GetMovie(context.Context, *MovieRequest) (*Movie, error)
	GetProjections(context.Context, *Empty) (*ProjectionList, error)
	GetProjectionsByMovie(context.Context, *MovieRequest) (*ProjectionList, error)
	GetProjection(context.Context, *ProjectionRequest) (*Projection, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) GetMovies(context.Context, *Empty) (*MovieList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMovies not implemented")
}
func (UnimplementedCatalogServiceServer) GetMovie(context.Context, *MovieRequest) (*Movie, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMovie not implemented")
}
func (UnimplementedCatalogServiceServer) GetProjections(context.Context, *Empty) (*ProjectionList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjections not implemented")
}
func (UnimplementedCatalogServiceServer) GetProjectionsByMovie(context.Context, *MovieRequest) (*ProjectionList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectionsByMovie not implemented")
}
func (UnimplementedCatalogServiceServer) GetProjection(context.Context, *ProjectionRequest) (*Projection, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjection not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_GetMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetMovies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetMovies(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetMovie(ctx, req.(*MovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetProjections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetProjections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetProjections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetProjections(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetProjectionsByMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetProjectionsByMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetProjectionsByMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetProjectionsByMovie(ctx, req.(*MovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetProjection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetProjection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetProjection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetProjection(ctx, req.(*ProjectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovies",
			Handler:    _CatalogService_GetMovies_Handler,
		},
		{
			MethodName: "GetMovie",
			Handler:    _CatalogService_GetMovie_Handler,
		},
		{
			MethodName: "GetProjections",
			Handler:    _CatalogService_GetProjections_Handler,
		},
		{
			MethodName: "GetProjectionsByMovie",
			Handler:    _CatalogService_GetProjectionsByMovie_Handler,
		},
		{
			MethodName: "GetProjection",
			Handler:    _CatalogService_GetProjection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/proto/catalog.proto",
}
